"""
Linear Diffusion Test — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TheoryBuilder


def build():
    return (
        TheoryBuilder('Linear Diffusion Test', n_populations=0)
        .physical_field('phi', indexed=True, spatial_dim=1)
        .parameter('mu', default=1.0, domain='positive')
        .parameter('D', default=1.0, domain='positive')
        .parameter('T', default=1.0, domain='positive')
        .set_action_text('phit*((Dt + mu - D*Laplacian)*phi) - T*phit^2')
        .equation(lhs='(Dt + mu - D*Laplacian)*phi', rhs='0')
        .boundary('infinite')
        .initial('stationary')
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'tau_max': 50.0,
    'tau_step': 0.5,
    'recommended_external_fields': [('phi', 1), ('phi', 2)],
    'fixed_point_index_default': 0,
}
