"""
My Stochastic Theory — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TheoryBuilder


def build():
    return (
        TheoryBuilder('My Stochastic Theory')
        .population('E', size=2, description='Excitatory')
        .population('I', size=2, description='Inhibitory')
        .physical_field('nE', population='E', description='spike train')
        .physical_field('vE', population='E', description='voltage')
        .physical_field('nI', population='I')
        .physical_field('vI', population='I')
        .parameter('tauE', default=[10, 9.5], indexed_by=['E'])
        .parameter('tauI', default=[8, 7], indexed_by=['I'])
        .parameter('EmE', default=[0.7, 0.72], indexed_by=['E'])
        .parameter('EmI', default=[0.4, 0.42], indexed_by=['I'])
        .parameter('wEE', default=[
    [0.25, 0.22],
    [0.21, 0.19],
], indexed_by=['E', 'E'])
        .parameter('wEI', default=[
    [0.12, 0.15],
    [0.13, 0.1],
], indexed_by=['E', 'I'])
        .parameter('wIE', default=[
    [0.19, 0.17],
    [0.15, 0.12],
], indexed_by=['I', 'E'])
        .parameter('wII', default=[
    [0.12, 0.13],
    [0.14, 0.15],
], indexed_by=['I', 'I'])
        .parameter('aE', default=[0.37, 0.41], indexed_by=['E'])
        .parameter('aI', default=[0.23, 0.28], indexed_by=['I'])
        .parameter('taugEE', default=[
    [4, 4],
    [3, 3],
], indexed_by=['E', 'E'])
        .parameter('taugEI', default=[
    [2, 1],
    [1, 3],
], indexed_by=['E', 'I'])
        .parameter('taugIE', default=[
    [5, 6],
    [2, 1],
], indexed_by=['I', 'E'])
        .parameter('taugII', default=[
    [1.5, 1.2],
    [1.1, 1.0],
], indexed_by=['I', 'I'])
        .define_function('phiE', args=['vE'], expression='aE[i] * vE', population='E', description='transfer (exc)')
        .define_function('phiI', args=['vI'], expression='aI[i] * vI', population='I', description='transfer (inh)')
        .define_kernel('gEE', time_expr='(1/taugEE[i,j])*exp(-t/taugEE[i,j])*heaviside(t)', freq_image='1/(1+I*omega*tau_g)', latex_name='gEE', indexed_by=['E', 'E'])
        .define_kernel('gEI', time_expr='(1/taugEI[i,j])*exp(-t/taugEI[i,j])*heaviside(t)', latex_name='gEI', indexed_by=['E', 'I'])
        .define_kernel('gIE', time_expr='(1/taugIE[i,j])*exp(-t/taugIE[i,j])*heaviside(t)', latex_name='gIE', indexed_by=['I', 'E'])
        .define_kernel('gII', time_expr='(1/taugII[i,j])*exp(-t/taugII[i,j])*heaviside(t)', latex_name='gII', indexed_by=['I', 'I'])
        .set_action_text('''
            sum( nEt[i]*nE[i] 
            - (exp(nEt[i])-1)*phiE[i](vE[i]) 
            + vEt[i]*((tauE[i]*Dt + 1)*vE[i] - EmE[i] 
            - sum(wEE[i,j]*gEE[i,j]*nE[j] for j in E)
            - sum(wEI[i,j]*gEI[i,j]*nI[j] for j in I)
            for i in E)
            + sum( nIt[i]*nI[i]
            - (exp(nIt[i])-1)*phiI[i](vI[i])
            + vIt[i]*((tauI[i]*Dt + 1)*vI[i] - EmI[i]
            - sum(wIE[i,j]*gIE[i,j]*nE[j] for j in E)
            - sum(wII[i,j]*gII[i,j]*nI[j] for j in I)
            for i in I)
        ''')
        .set_mf_equation('vEstar', 'EmE[i] + sum(wEE[i, j] * nEstar[j] for j in E) + sum(wEI[i,j]*nIstar[j] for j in I)')
        .set_mf_equation('nEstar', 'phiE[i](vE[i])')
        .set_mf_equation('vIstar', 'EmI[i] + sum(wIE[i,j]*nEstar[j] for j in E) + sum(wII[i,j]*nIstar[j] for j in I)')
        .set_mf_equation('nIstar', 'phiI[i](vI[i])')
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('nE', 1), ('nE', 2)],
    'tau_max': 20.0,
    'tau_step': 2.5,
}
