"""
OU Quartic Double Well — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TemporalTheoryBuilder


def build():
    return (
        TemporalTheoryBuilder('OU Quartic Double Well')
        .population('pop', size=1)
        .physical_field('x', population='pop', description='variable')
        .parameter('mu', default=0.1, domain='real')
        .parameter('eps', default=0.1, domain='positive')
        .parameter('D', default=1.0, domain='positive')
        .set_action_text('sum(xt[i]*((Dt+mu)*x[i] + eps*x[i]^3) - D*xt[i]^2 for i in pop)')
        .equation(lhs='(Dt+mu)*x[i]', rhs='-eps*x[i]^3', population='pop')
        .stability_analysis(True)
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('x', 1)],
    'tau_max': 50.0,
    'tau_step': 0.5,
    'fixed_point_index_default': 0,
}
