"""
OU Quartic Two Dim Color-Corr — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TheoryBuilder


def build():
    return (
        TheoryBuilder('OU Quartic Two Dim Color-Corr', n_populations=0)
        .physical_field('x', indexed=True, description='variable1')
        .physical_field('y', indexed=True, description='variable2')
        .parameter('mu1', default=1.0, domain='real')
        .parameter('mu2', default=1.0, domain='real')
        .parameter('eps1', default=0.05, domain='positive')
        .parameter('eps2', default=0.05, domain='positive')
        .parameter('J1', default=0.5, domain='real')
        .parameter('J2', default=0.5, domain='real')
        .parameter('D1', default=1.0, domain='positive')
        .parameter('D2', default=1.0, domain='positive')
        .parameter('rho', default=0.5, domain='real')
        .parameter('tauc', default=10.0, domain='positive')
        .declare_cgf_term('Cxx', response_legs=['xt', 'xt'], order=2, coefficient='D1/tauc', kernel='exp(-abs(tau)/tauc)')
        .declare_cgf_term('Cyy', response_legs=['yt', 'yt'], order=2, coefficient='D2/tauc', kernel='exp(-abs(tau)/tauc)')
        .declare_cgf_term('Cxy', response_legs=['xt', 'yt'], order=2, coefficient='rho*sqrt(D1*D2)/tauc', kernel='exp(-abs(tau)/tauc)')
        .set_action_text('xt*((Dt+mu1)*x + eps1*x^3 - J1*y) + yt*((Dt+mu2)*y + eps2*y^3 - J2*x)')
        .equation(lhs='(Dt+mu1)*x', rhs='-eps1*x^3 + J1*y')
        .equation(lhs='(Dt+mu2)*y', rhs='-eps2*y^3 + J2*x')
        .stability_analysis(True)
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('x', 1)],
    'tau_max': 50.0,
    'tau_step': 0.5,
    'fixed_point_index_default': 0,
}
