"""
OU Quartic Double Well — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TemporalTheoryBuilder


def build():
    return (
        TemporalTheoryBuilder('OU Quartic Double Well')
        .population('pop', size=1)
        .physical_field('x', population='pop', description='variable')
        .parameter('mu', default=0.1, domain='real')
        .parameter('eps', default=0.1, domain='positive')
        .parameter('D', default=1.0, domain='positive')
        .set_action_text('sum(xt[i]*((Dt+mu)*x[i] + eps*x[i]^3) - D*xt[i]^2 for i in pop)')
        .equation(lhs='(Dt+mu)*x[i]', rhs='-eps*x[i]^3', population='pop')
        .stability_analysis(True)
        .build()
    )


# Perturbative-regime run defaults (override the build()'s near-bifurcation
# author default mu=0.1).  The loop expansion parameter is g_eff ≈ eps·D/mu²;
# at mu=1, eps=0.1, D=1 → g_eff=0.1 (mildly perturbative, runs cleanly).
# Lower mu toward 0 (or mu<0 for the genuine double well) to stress the
# series — but Phase J runtime explodes with |mu| at ell≥1.
DEFAULT_FUNDAMENTAL = {
    'mu': 1.0,
    'eps': 0.1,
    'D': 1.0,
}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('dx', 1), ('dx', 1)],
    'tau_max': 50.0,
    'tau_step': 0.5,
    'fixed_point_index_default': 0,
}
