"""
OU Quartic Two Dim — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TheoryBuilder


def build():
    return (
        TheoryBuilder('OU Quartic Two Dim', n_populations=0)
        .physical_field('x', indexed=True, description='variable1')
        .physical_field('y', indexed=True, description='variable2')
        .parameter('mu1', default=1.0, domain='real')
        .parameter('mu2', default=1.0, domain='real')
        .parameter('eps1', default=0.05, domain='positive')
        .parameter('eps2', default=0.05, domain='positive')
        # NOTE on defaults: at J1=J2=mu1=mu2=1 the linear stability
        # matrix at (0, 0) has a zero eigenvalue (system on the
        # bifurcation), so the DAE solver flags the trivial saddle
        # 'not stable' and the verifier falls back to nonsense.
        # Keep |J1·J2| < |mu1·mu2| for a genuinely-stable origin —
        # 0.5·0.5 < 1·1 gives σ = -0.5, -1.5 at (0, 0).
        .parameter('J1', default=0.5, domain='real')
        .parameter('J2', default=0.5, domain='real')
        .parameter('D1', default=1.0, domain='positive')
        .parameter('D2', default=1.0, domain='positive')
        .set_action_text('xt*((Dt+mu1)*x + eps1*x^3 - J1*y) - D1*xt^2 + yt*((Dt+mu2)*y + eps2*y^3 - J2*x) - D2*yt^2')
        .equation(lhs='(Dt+mu1)*x', rhs='-eps1*x^3 + J1*y')
        .equation(lhs='(Dt+mu2)*y', rhs='-eps2*y^3 + J2*x')
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('x', 1)],
    'tau_max': 50.0,
    'tau_step': 0.5,
    'fixed_point_index_default': 0,
}
