"""
OU Quartic Colored — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TemporalTheoryBuilder


def build():
    return (
        TemporalTheoryBuilder('OU Quartic Colored', n_populations=0)
        .physical_field('x', indexed=True, description='variable')
        .parameter('mu', default=0.1, domain='real')
        .parameter('eps', default=0.1, domain='positive')
        .parameter('D', default=1.0, domain='positive')
        .parameter('tauc', default=1.0, domain='positive')
        .declare_cgf_term('CXX', response_legs=['xt', 'xt'], order=2, coefficient='2*D/tauc', kernel='exp(-abs(tau)/tauc)')
        .set_action_text('xt*((Dt+mu)*x + eps*x^3)')
        .equation(lhs='(Dt+mu)*x', rhs='-eps*x^3')
        .stability_analysis(True)
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'tau_max': 50.0,
    'tau_step': 0.5,
    'recommended_external_fields': [('x', 1)],
    'fixed_point_index_default': 0,
}
