"""
Quadratic Hawkes 2-population — text-driven theory file.

Generated by the theory-input UI (or hand-written following the same
pattern).  Loaded by ``notebooks/theory_runner.ipynb`` to compute
cumulants on this theory.

Schema
------
Every saved theory file in this directory exposes:

  * ``build()`` returning a ``model`` dict ready for
    ``pipeline.compute_cumulants``.
  * ``DEFAULT_FUNDAMENTAL``: a dict of suggested numerical parameter
    values (overrideable in the runner).
  * ``METADATA`` (optional): free-form info — k, max_ell suggestions,
    notes, references.

Edit by hand or regenerate from the UI.
"""
from pipeline.theory import TheoryBuilder


def build():
    """Quadratic Hawkes 2-pop with exponential synaptic kernel.

      φ(v) = a · v²       (quadratic transfer function)
      g(t) = (1/τ_g) · exp(-t/τ_g) · Θ(t)   (exp synapse)
    """
    return (
        TheoryBuilder('Quadratic Hawkes 2-pop', n_populations=2)

        # ── Field variables ───────────────────────────────────────
        # Just declare the natural physical fields — the framework
        # auto-creates the fluctuation field (d-prefixed), the
        # conjugate response field (-t suffixed), and the saddle
        # parameter (-star suffixed).
        .physical_field('n')
        .physical_field('v')

        # ── Parameters ────────────────────────────────────────────
        .parameter('E',     indexed=True)
        .parameter('tau',   default=10.0, domain='positive')
        .parameter('a',     default=0.44)
        .parameter('tau_g', default=2.5,  domain='positive')
        .parameter('w',     indexed='matrix')

        # ── Functions and kernels ────────────────────────────────
        .define_function('phi', args=['v'], expression='a * v^2',
                         latex=r'\varphi')
        .define_kernel('g', freq_image='1 / (1 + I*omega*tau_g)',
                       latex_name='g')

        # ── Action ───────────────────────────────────────────────
        # Hawkes Poisson MSR-JD action written in physical fields.
        # ``n[i]`` (full field) is automatically expanded to
        # ``nstar[i] + dn[i]`` by the compiler, and ``phi[i](v[i])``
        # is recognized as the saddle-shifted formal Taylor target
        # (the framework adds renames at vstar[i] so the
        # phi0_<i+1>, phi1_<i+1>, ... substitution pipeline applies
        # transparently).
        .set_action_text('''
            sum(
                nt[i] * n[i]
                - (exp(nt[i]) - 1) * phi[i](v[i])
                + vt[i] * (
                    (tau * Dt + 1) * v[i]
                    - E[i]
                    - sum(w[i, j] * g * n[j] for j in pop)
                )
                for i in pop
            )
        ''')

        # ── Mean-field equations ─────────────────────────────────
        .set_mf_equation('vstar',
            'E[i] + sum(w[i, j] * g * nstar[j] for j in pop)')
        .set_mf_equation('nstar', 'phi(vstar[i])')

        .build()
    )


DEFAULT_FUNDAMENTAL = {
    'E':     [0.78, 0.81],
    'w':     [[0.30, 0.25],
              [0.30, 0.35]],
    'tau':   10.0,
    'a':     0.44,
    'tau_g': 2.5,
}


METADATA = {
    'description':   'Quadratic Hawkes 2-pop with exp synaptic kernel.',
    'k_default':     2,
    'ell_default':   0,
    'recommended_external_fields': [('n', 1), ('n', 2)],
    'tau_max':       50.0,
    'tau_step':      0.5,
}
