"""
Quadratic Hawkes 2-population — text-driven theory file.

Generated by the theory-input UI (or hand-written following the same
pattern).  Loaded by ``notebooks/theory_runner.ipynb`` to compute
cumulants on this theory.

Schema
------
Every saved theory file in this directory exposes:

  * ``build()`` returning a ``model`` dict ready for
    ``pipeline.compute_cumulants``.
  * ``DEFAULT_FUNDAMENTAL``: a dict of suggested numerical parameter
    values (overrideable in the runner).
  * ``METADATA`` (optional): free-form info — k, max_ell suggestions,
    notes, references.

Edit by hand or regenerate from the UI.
"""
from pipeline.theory import TheoryBuilder


def build():
    """Quadratic Hawkes 2-pop with exponential synaptic kernel.

      φ(v) = a · v²       (quadratic transfer function)
      g(t) = (1/τ_g) · exp(-t/τ_g) · Θ(t)   (exp synapse)
    """
    return (
        TheoryBuilder('Quadratic Hawkes 2-pop', n_populations=2)

        # ── Field variables ───────────────────────────────────────
        .response_field('nt', indexed=True, latex=r'\tilde n')
        .response_field('vt', indexed=True, latex=r'\tilde v')
        .physical_field('dn', indexed=True, natural_name='n',
                        latex=r'\delta\dot n')
        .physical_field('dv', indexed=True, natural_name='v',
                        latex=r'\delta v')

        # ── Parameters ────────────────────────────────────────────
        .parameter('nstar', indexed=True, domain='positive',
                   mean_field=True, natural_name='n')
        .parameter('vstar', indexed=True,
                   mean_field=True, natural_name='v')
        .parameter('E',     indexed=True)
        .parameter('tau',   default=10.0, domain='positive')
        .parameter('a',     default=0.44)
        .parameter('tau_g', default=2.5,  domain='positive')
        .parameter('w',     indexed='matrix')

        # ── Functions and kernels ────────────────────────────────
        .define_function('phi', args=['v'], expression='a * v^2',
                         latex=r'\varphi')
        .define_kernel('g', freq_image='1 / (1 + I*omega*tau_g)',
                       latex_name='g')

        # ── Action S_i (per-population integrand) ────────────────
        # Hawkes Poisson MSR-JD action.  ``phi(dv[i])`` is the formal
        # Taylor target; framework substitutes phi(0) → nstar[i].
        .set_action_text('''
            nt[i] * (nstar[i] + dn[i])
            - (exp(nt[i]) - 1) * phi(dv[i])
            + vt[i] * (
                (tau * Dt + 1) * dv[i]
                + vstar[i] - E[i]
                - sum(w[i, j] * g * (nstar[j] + dn[j]) for j in pop)
            )
        ''')

        # ── Mean-field equations ─────────────────────────────────
        .set_mf_equation('vstar',
            'E[i] + sum(w[i, j] * g * nstar[j] for j in pop)')
        .set_mf_equation('nstar', 'phi(vstar[i])')

        .build()
    )


DEFAULT_FUNDAMENTAL = {
    'E':     [0.78, 0.81],
    'w':     [[0.30, 0.25],
              [0.30, 0.35]],
    'tau':   10.0,
    'a':     0.44,
    'tau_g': 2.5,
}


METADATA = {
    'description':   'Quadratic Hawkes 2-pop with exp synaptic kernel.',
    'k_default':     2,
    'ell_default':   0,
    'recommended_external_fields': [('n', 1), ('n', 2)],
    'tau_max':       50.0,
    'tau_step':      0.5,
}
