"""
Single pop Dendritic Linear — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TemporalTheoryBuilder


def build():
    return (
        TemporalTheoryBuilder('Single pop Dendritic Linear')
        .population('E', size=2, description='Excitatory')
        .physical_field('nS', population='E', description='Somatic Spike Train')
        .physical_field('nD', population='E', description='Dendritic Spike Train')
        .parameter('wSS', default=[
    [0.0, 0.0],
    [0.0, 0.0],
], indexed_by=['E', 'E'], domain='real')
        .parameter('wSD', default=[
    [0.1, 0.0],
    [0.0, 0.1],
], indexed_by=['E', 'E'], domain='real')
        .parameter('wDS', default=[
    [0.1, 0.1],
    [0.1, 0.1],
], indexed_by=['E', 'E'], domain='real')
        .parameter('wDD', default=[
    [0.0, 0.0],
    [0.0, 0.0],
], indexed_by=['E', 'E'], domain='real')
        .parameter('tauS', default=[1.0, 1.0], indexed_by=['E'], domain='positive', description='Somatic Time Constant')
        .parameter('tauD', default=[1.0, 1.0], indexed_by=['E'], domain='positive', description='Dendritic Time Constant')
        .parameter('ES', default=[0.5, 0.5], indexed_by=['E'], domain='real', description='Somatic Resting Potential')
        .parameter('ED', default=[0.5, 0.5], indexed_by=['E'], domain='real', description='Dendritic Resting Potential')
        .define_kernel('gS', time_expr='(1/tauS[i])*exp(-t/tauS[i])*heaviside(t)', latex_name='gS', indexed_by=['E'])
        .define_kernel('gD', time_expr='(1/tauD[i])*exp(-t/tauD[i])*heaviside(t)', latex_name='gD', indexed_by=['E'])
        .set_action_text('''
            sum( nSt[i]*nS[i] + nDt[i]*nD[i]
            - (exp(nSt[i])-1)*(ES[i]
            + sum(wSS[i,j]*Conv(gS[i],nS[j]) + wSD[i,j]*Conv(gS[i],nD[j]) for j in E))
            - nS[i]*log(1 + (exp(nDt[i])-1)*(ED[i]
            + sum(wDS[i,j]*Conv(gD[i],nS[j]) + wDD[i,j]*Conv(gD[i],nD[j]) for j in E)))
            for i in E)
        ''')
        .equation(lhs='nS[i]', rhs='ES[i] + sum(wSS[i,j]*nS[j] + wSD[i,j]*nD[j] for j in E)', population='E')
        .equation(lhs='nD[i]', rhs='nS[i]*(ED[i] + sum(wDS[i,j]*nS[j] + wDD[i,j]*nD[j] for j in E))', population='E')
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('nS', 1), ('nS', 2)],
    'tau_max': 20.0,
    'tau_step': 2.5,
    'fixed_point_index_default': 0,
}
