"""
Single population Linear Delta Spikes Test — text-driven theory file.

Spikes-side formulation of the linear-rate δ-synapse Hawkes process.
Obtained from ``single_population_linear_delta_voltage_test`` by
algebraically substituting the v EOM: with linear φ and δ-synapse,
v_i(t) = Em_i + Σ_j w_ij·(h_i ∗ n_j)(t)  where  h_i(t) =
(1/τ_i)·exp(-t/τ_i)·θ(t) is the membrane filter.  We keep ``v`` as a
*slave* field (no time derivative) so the framework's φ(v) Taylor-
expansion machinery still fires cleanly; the only structural difference
from the voltage theory is the membrane filter now lives in the
synaptic kernel ``Conv(g_i, n_j)`` instead of being implicit in the v
ODE.  That puts the convolutional vertex on the ``vt``-equation, which
is what we want to stress-test.

Both theories describe the same physical process (linear δ-synapse
Hawkes) and must produce identical n-correlators at every order.  The
third moment ⟨n n n⟩ is the test target.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TheoryBuilder


def build():
    return (
        TheoryBuilder('Single population Linear Delta Spikes Test')
        .population('E', size=2, description='Excitatory')
        .physical_field('n', population='E', description='spike train')
        .physical_field('v', population='E', description='voltage (algebraic slave to n)')
        .parameter('Em', default=[0.8, 0.78], indexed_by=['E'], domain='positive')
        .parameter('tau', default=[10, 9], indexed_by=['E'], domain='positive')
        .parameter('w', default=[
    [0.0, 0.25],
    [0.2, 0.0],
], indexed_by=['E', 'E'], domain='positive')
        .define_function('phi', args=['v'], expression='v', population='E')
        # Per-population membrane filter from the integrated-out v dynamics.
        # In the voltage theory g = δ(t); here g is the exponential
        # membrane filter so Conv(g, n) carries the time-domain shape
        # that previously came from the v ODE.
        .define_kernel('g',
                       time_expr='(1/tau[i])*exp(-t/tau[i])*heaviside(t)',
                       latex_name='g', indexed_by=['E'])
        # v has NO time derivative — vt equation imposes the algebraic
        # constraint v_i = Em_i + Σ_j w_ij · Conv(g_i, n_j) pointwise.
        # That places the Conv vertex on the vt-equation, exactly the
        # piece we want the diagrammatic machinery to handle.
        .set_action_text('''
            sum( nt[i]*n[i]
            - (exp(nt[i])-1)*phi[i](v[i])
            + vt[i]*(v[i] - Em[i] - sum(w[i,j]*Conv(g[i], n[j]) for j in E))
            for i in E)
        ''')
        .set_mf_equation('vstar', '(Em[i] + sum(w[i, j]*nstar[j] for j in E))')
        .set_mf_equation('nstar', 'phi[i](vstar[i])')
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('nE', 1), ('nE', 2)],
    'tau_max': 20.0,
    'tau_step': 2.5,
}
