"""
Single population Linear Delta Voltage Test — text-driven theory file.

Linear-rate δ-synapse Hawkes with explicit v dynamics.  Identical
physics to ``single_population_linear_delta_spikes_test`` (which
integrates v out via a slaved field) — the two theories must produce
identical n-correlators at every order.

Ported to the new ``.equation(lhs=..., rhs=...)`` API which feeds the
DAE-based multi-root MF solver (``pipeline._mean_field_dae``).  The
legacy ``set_mf_equation(...)`` declarations are auto-derived from the
``.equation(...)`` calls at build time (TheoryBuilder._auto_populate_
mf_eqs_from_equations), so downstream code is unchanged.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TheoryBuilder


def build():
    return (
        TheoryBuilder('Single population Linear Delta Voltage Test')
        .population('E', size=2, description='Excitatory')
        .physical_field('n', population='E', description='spike train')
        .physical_field('v', population='E', description='voltage')
        .parameter('Em', default=[0.8, 0.78], indexed_by=['E'], domain='positive')
        .parameter('tau', default=[10, 9], indexed_by=['E'], domain='positive')
        .parameter('w', default=[
    [0.0, 0.25],
    [0.2, 0.0],
], indexed_by=['E', 'E'], domain='positive')
        .define_function('phi', args=['v'], expression='v', population='E')
        .define_kernel('g', time_expr='dirac_delta(t)', latex_name='g')
        .set_action_text('''
            sum( nt[i]*n[i]
            - (exp(nt[i])-1)*phi[i](v[i])
            + vt[i]*((tau[i]*Dt + 1)*v[i] - Em[i]
            - sum(w[i,j]*Conv(g,n[j]) for j in E))
            for i in E)
        ''')
        # DAE form: one residual per call.  Dt allowed on LHS only;
        # the MF solver substitutes Dt → 0 to get the algebraic
        # system, and uses ∂/∂Dt for the linearization Jacobian.
        .equation(
            lhs='(tau[i]*Dt + 1) * v[i]',
            rhs='Em[i] + sum(w[i, j]*n[j] for j in E)',
            population='E',
        )
        .equation(
            lhs='n[i]',
            rhs='phi[i](v[i])',
            population='E',
        )
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('nE', 1), ('nE', 2)],
    'tau_max': 20.0,
    'tau_step': 2.5,
}
