"""
Single population Linear Delta Voltage Test — text-driven theory file.

Generated by the theory-input UI (``notebooks/theory_builder.ipynb``).
Loaded by ``notebooks/theory_runner.ipynb``.
"""
from pipeline.theory import TheoryBuilder


def build():
    return (
        TheoryBuilder('Single population Linear Delta Voltage Test')
        .population('E', size=2, description='Excitatory')
        .physical_field('n', population='E', description='spike train')
        .physical_field('v', population='E', description='voltage')
        .parameter('Em', default=[0.8, 0.78], indexed_by=['E'], domain='positive')
        .parameter('tau', default=[10, 9], indexed_by=['E'], domain='positive')
        .parameter('w', default=[
    [0.0, 0.25],
    [0.2, 0.0],
], indexed_by=['E', 'E'], domain='positive')
        .define_function('phi', args=['v'], expression='v')
        .define_kernel('g', time_expr='dirac_delta(t)', latex_name='g')
        .set_action_text('''
            sum( nt[i]*n[i] 
            - (exp(nt[i])-1)*phi[i](v[i]) 
            + vt[i]*((tau[i]*Dt + 1)*v[i] - Em[i]
            - sum(w[i,j]*Conv(g,n[j]) for j in E))
            for i in E)
        ''')
        .set_mf_equation('vstar', '(Em[i] + sum(w[i, j]*nstar[j] for j in E))')
        .set_mf_equation('nstar', 'phi(vstar[i])')
        .build()
    )


DEFAULT_FUNDAMENTAL = {}


METADATA = {
    'k_default': 2,
    'ell_default': 0,
    'recommended_external_fields': [('nE', 1), ('nE', 2)],
    'tau_max': 20.0,
    'tau_step': 2.5,
}
