"""
models/hawkes_linear_expg_gtas.py
=================================
**Linear** Hawkes 2-population network *with two correlated external
neurons* generated by a GTaS (Generalized Thinning and Shift)
process — Bernoulli participation + Gaussian shifts.  Same external
machinery as ``hawkes_quad_expg_gtas`` but with a linear cortical
transfer function ``phi_i(v) = a · v``.

Network topology
----------------
    external[1] ──J──▶ cortical[1]
    external[2] ──J──▶ cortical[2]            (one-to-one feedforward, weight w_X)
    cortical[1] ⇄ cortical[2]                 (recurrent linear Hawkes)

Cortical layer (linear phi)
---------------------------
    phi_i(v) = a · v                          (linear gain, no v^2)
    n*_i = phi_i(v*_i) = a · v*_i
    v*_i = E_i + sum_j w_{ij} g n*_j  +  w_X · g · b_X
    (b_X = lambda_X · p_part is the GTaS marginal Poisson rate per cell)

Combined MF (closed form, no quadratic):
    n*_i = a · (E_i + sum_j w_{ij} n*_j + w_X · b_X)
       =>  n*  = a · (I − a W)^{-1} · (E + w_X · b_X · 1)

External GTaS layer (identical to quad_expg_gtas)
-------------------------------------------------
Same Bernoulli + Gaussian process: marginal Poisson rate b_X per
cell, cumulant kernel
    κ^{(2)}_{ii}(τ) = b_X · δ(τ)               (auto, local)
    κ^{(2)}_{12}(τ) = lambda_X · p_part^2 · N(τ; mu_diff, sigma_diff^2)
                                              (cross, smooth)
The framework's ``correlated_noises`` block injects ``-W_m[mt]`` into
the action automatically; m̃-tilde legs reach cortical δn-leaves
through the feedforward chain via the (full) propagator.

Specializations vs ``hawkes_quad_expg_gtas``
--------------------------------------------
The action structure is unchanged.  Only the ``phi`` Taylor coefficients
change:

  * quad_expg_gtas:  phi1_i = 2 · a · vstar_i,  phi2_i = 2 · a, higher = 0
  * linear_expg_gtas: phi1_i = a,                phi_k_i = 0 for k ≥ 2

Consequence: the cortical interaction vertex set collapses (no
nonlinear ``nt^k · dv^l`` vertices for k+l ≥ 3 since phi has no
higher derivatives).  Tree-level k=2 only sees the bilinear (1,1)
sector and the noise sources (cortical Poisson + GTaS auto + GTaS
cross).  The (nt, dv) propagator block becomes ``-a`` (constant)
instead of ``-2 a vstar_i``.
"""

from sage.all import SR, exp, function, I, sqrt, pi, dirac_delta


# ---------------------------------------------------------------------------
# Local helper: Gaussian kernel  N(tau; mu, sigma^2)
# ---------------------------------------------------------------------------
def _gauss(tau, mu, sigma_sq):
    """Unit-area Gaussian density used by the GTaS cross-cumulant kernel."""
    return exp(-(tau - mu)**2 / (2 * sigma_sq)) / sqrt(2 * pi * sigma_sq)


# ---------------------------------------------------------------------------
# Population count (cortical only — externals are scalar-indexed below)
# ---------------------------------------------------------------------------
N_POP = 2
_pop  = list(range(N_POP))

# ---------------------------------------------------------------------------
# SR parameter symbols
# ---------------------------------------------------------------------------
_nstar = [SR.var(f'nstar{i+1}', domain='positive') for i in _pop]
_w     = [[SR.var(f'w{i+1}{j+1}') for j in _pop] for i in _pop]
_g     = SR.var('g')

# ---------------------------------------------------------------------------
# Model dict
# ---------------------------------------------------------------------------
HAWKES_MODEL: dict = {

    'name': ('Linear Hawkes 2-pop + GTaS external (phi = a v, '
             'exp filter tau_g, Bernoulli + Gaussian shifts)'),

    # -----------------------------------------------------------------------
    # Index sets
    # -----------------------------------------------------------------------
    'index_sets': {'pop': _pop},

    # -----------------------------------------------------------------------
    # Response fields
    # -----------------------------------------------------------------------
    'response_fields': [
        {'name': 'nt', 'indexed': True, 'latex': r'\tilde{n}',
         'description': 'response field conjugate to spike train'},
        {'name': 'vt', 'indexed': True, 'latex': r'\tilde{v}',
         'description': 'response field conjugate to voltage'},
        {'name': 'mt', 'indexed': True, 'latex': r'\tilde{m}',
         'description': 'response field conjugate to GTaS external '
                        'fluctuation dm (one per cortical leg)'},
    ],

    # -----------------------------------------------------------------------
    # Physical fluctuation fields
    # -----------------------------------------------------------------------
    'physical_fields': [
        {'name': 'dn', 'indexed': True, 'latex': r'\delta\dot{n}',
         'description': 'spike-train fluctuation around MF background'},
        {'name': 'dv', 'indexed': True, 'latex': r'\delta v',
         'description': 'voltage fluctuation around MF background'},
        {'name': 'dm', 'indexed': True, 'latex': r'\delta m',
         'description': 'GTaS external fluctuation around mean b_X = '
                        'lambda_X * p_part (one per cortical leg, '
                        'zero-mean by construction)'},
    ],

    # -----------------------------------------------------------------------
    # Scalar parameters
    # -----------------------------------------------------------------------
    'parameters': [
        {'name': 'nstar', 'indexed': True,  'domain': 'positive',
         'description': 'background firing rate  n*_i = a · v*_i'},
        {'name': 'vstar', 'indexed': True,
         'description': 'background voltage'},
        {'name': 'mstar', 'indexed': True, 'domain': 'positive',
         'description': 'background external rate  m*_i = b_X = '
                        'lambda_X * p_part (marginal Poisson rate per '
                        'external cell)'},
        {'name': 'E',     'indexed': True,
         'description': 'external constant drive (cortical)'},
        {'name': 'tau',   'indexed': False, 'domain': 'positive',
         'description': 'membrane time constant'},
        {'name': 'a',     'indexed': False,
         'description': 'linear transfer-function gain: phi(v) = a v'},
        {'name': 'tau_g', 'indexed': False, 'domain': 'positive',
         'description': 'synaptic exponential filter timescale'},
        {'name': 'w',     'indexed': True,
         'description': 'recurrent synaptic weight matrix w_{ij}'},
        # ---- GTaS external-layer parameters ----
        {'name': 'w_X',   'indexed': False,
         'description': 'feedforward synaptic weight (external -> cortical, '
                        'one-to-one)'},
        {'name': 'lambda_X', 'indexed': False, 'domain': 'positive',
         'description': 'mother Poisson rate of GTaS external process'},
        {'name': 'p_part',   'indexed': False, 'domain': 'positive',
         'description': 'Bernoulli participation probability per external cell'},
        {'name': 'mu_shift_diff',     'indexed': False,
         'description': 'mean shift difference between externals: '
                        'mu_shift[1] - mu_shift[0]'},
        {'name': 'sigma_shift_diff_sq', 'indexed': False, 'domain': 'positive',
         'description': 'variance of shift difference: Sigma[0,0] + '
                        'Sigma[1,1] - 2 Sigma[0,1]'},
    ],

    # -----------------------------------------------------------------------
    # Kernels
    # -----------------------------------------------------------------------
    'kernels': [
        {'name': 'g', 'sage_name': 'z_g', 'latex_name': 'g',
         'description': 'exponential synaptic filter, unit integral'},
    ],

    # -----------------------------------------------------------------------
    # Operators
    # -----------------------------------------------------------------------
    'operators': [
        {'name': 'Dt', 'sage_name': 'Dt', 'latex_name': r'\partial_t',
         'description': r'd/dt  (time derivative)'},
    ],

    # -----------------------------------------------------------------------
    # Nonlinear functions  (phi linear)
    # -----------------------------------------------------------------------
    'functions': [
        {
            'name':         'phi',
            'indexed':      True,
            'deriv_prefix': 'phi',
            'latex':        r'\varphi',
            'description':  'linear gain function phi_i(v) = a v',
            'expression':   lambda i, v: function(f'phi_{i+1}')(v),
        },
    ],

    # -----------------------------------------------------------------------
    # Namespace-level substitutions
    # -----------------------------------------------------------------------
    'mf_substitutions': [
        {
            'name':  'w',
            'value': lambda ns: [[SR.var(f'w{i+1}{j+1}') for j in ns.pop]
                                 for i in ns.pop],
        },
        {
            'name':  'ndot_bg',
            'value': lambda ns: [+ns.nstar[i] for i in ns.pop],
        },
    ],

    # -----------------------------------------------------------------------
    # MF background conditions
    #
    # Same structure as quad_expg_gtas: vstar absorbs cortical recurrence
    # AND the GTaS feedforward mean (with `g` kernel symbol on both
    # sides for symbolic tadpole cancellation).
    # -----------------------------------------------------------------------
    'mf_bg_conditions': lambda ns: {
        **{SR.var(f'phi0_{i+1}'): ns.nstar[i] for i in ns.pop},
        **{ns.vstar[i]: (ns.E[i]
                         + sum(ns.w[i][j] * ns.g * ns.nstar[j]
                               for j in ns.pop)
                         + ns.w_X * ns.g * ns.lambda_X * ns.p_part)
           for i in ns.pop},
    },

    # -----------------------------------------------------------------------
    # Specializations  (linear phi)
    #
    #   phi1_i = a       (constant, no vstar dependence)
    #   phi_k_i = 0      for k >= 2  (no nonlinear vertices)
    # -----------------------------------------------------------------------
    'specializations': lambda ns: {
        **{SR.var(f'phi1_{i+1}'): SR.var('a') for i in ns.pop},
        **{SR.var(f'phi{k}_{i+1}'): SR(0)
           for k in range(2, ns._taylor_order + 1)
           for i in ns.pop},
    },

    # -----------------------------------------------------------------------
    # Kernel frequency-space image
    # -----------------------------------------------------------------------
    'kernel_ft_image': lambda ns, omega: {
        ns.g: SR(1) / (SR(1) + I * omega * ns.tau_g),
    },

    # -----------------------------------------------------------------------
    # Concrete transfer function  (linear)
    # -----------------------------------------------------------------------
    'phi_concrete': lambda ns, i, v: SR.var('a') * v,

    # -----------------------------------------------------------------------
    # Mean-field self-consistency equations  (linear in nstar)
    #
    #   n*_i = a · (E_i + sum_j w_{ij} · n*_j + w_X · lambda_X · p_part)
    #   m*_i = b_X = lambda_X · p_part
    # -----------------------------------------------------------------------
    'mf_equations': lambda ns: [
        ns.nstar[i] == SR.var('a') * (
            ns.E[i]
            + sum(ns.w[i][j] * ns.nstar[j] for j in ns.pop)
            + SR.var('w_X') * SR.var('lambda_X') * SR.var('p_part')
        )
        for i in ns.pop
    ] + [
        ns.mstar[i] == SR.var('lambda_X') * SR.var('p_part')
        for i in ns.pop
    ],

    # -----------------------------------------------------------------------
    # Background rate convention
    # -----------------------------------------------------------------------
    'background_rate_convention': (
        'n_dot_i* = +phi_i(v_i*) = a * v_i*,     '
        'm_dot_i* = b_X = lambda_X * p_part     '
        '[Hawkes cortical (linear) saddle + GTaS external mean]'
    ),

    # -----------------------------------------------------------------------
    # Action  (identical structure to quad_expg_gtas; phi linearity is in
    # specializations, not in the action lambda)
    # -----------------------------------------------------------------------
    'action': lambda ns: sum(
        # Cortical Poisson term
        ns.nt[i] * (ns.ndot_bg[i] + ns.dn[i])
        - (exp(ns.nt[i]) - 1) * ns.phi(i, ns.dv[i])
        # Cortical voltage equation  (driven by feedforward mean + dm)
        + ns.vt[i] * (
            (ns.tau * ns.Dt + 1) * ns.dv[i]
            + ns.vstar[i] - ns.E[i]
            - sum(ns.w[i][j] * ns.g * (ns.nstar[j] + ns.dn[j])
                  for j in ns.pop)
            - ns.w_X * ns.g * (ns.lambda_X * ns.p_part + ns.dm[i])
        )
        # MSR source-pairing for the external fluctuation field
        + ns.mt[i] * ns.dm[i]
        for i in ns.pop
    ),

    # -----------------------------------------------------------------------
    # Correlated-noise declarations
    # See models/hawkes_quad_expg_gtas.py for the API reference.
    # The cumulants are identical (Bernoulli + Gaussian GTaS).
    # -----------------------------------------------------------------------
    'correlated_noises': {
        'X': {
            'physical_field':  'dm',
            'response_field':  'mt',
            'mean': lambda ns: ns.lambda_X * ns.p_part,
            'cumulants': {
                # κ^{(2)}_{ij}(τ) =
                #   {  b_X · δ(τ),                            i == j
                #   {  λ_X · p_part^2 · N(τ; μ_diff, σ_diff²), i != j
                2: lambda ns, i, j, tau: (
                    ns.lambda_X * ns.p_part * dirac_delta(tau)
                    if i == j else
                    ns.lambda_X * ns.p_part**2 * _gauss(
                        tau, ns.mu_shift_diff, ns.sigma_shift_diff_sq
                    )
                ),
            },
        },
    },
}
