"""
models/hawkes_quad_expg_gtas.py
===============================
**Quadratic** Hawkes 2-population network *with two correlated
external neurons* generated by a GTaS (Generalized Thinning and
Shift) process — Bernoulli participation + Gaussian shifts.  Each
external neuron projects feedforward (one-to-one) to a single
cortical neuron with weight ``W_X`` through the same exponential
synaptic filter ``g(t) = (1/tau_g) exp(-t/tau_g) Theta(t)`` used
recurrently.

Network topology
----------------
    external[1] ──J──▶ cortical[1]
    external[2] ──J──▶ cortical[2]            (one-to-one feedforward)
    cortical[1] ⇄ cortical[2]                 (recurrent quadratic Hawkes)

Cortical layer (unchanged from ``hawkes_quad_expg``)
----------------------------------------------------
    phi_i(v) = a v^2     (quadratic gain)
    n*_i = phi_i(v*_i) = a (v*_i)^2
    v*_i = E_i + sum_j w_{ij} n*_j  +  W_X * (lambda_X * p_part)
                                    \____________________/
                                    constant feedforward mean

External GTaS process (Trousdale et al. 2013)
---------------------------------------------
A 2-cell GTaS process is fully characterised here by:

    * lambda_X  -- mother Poisson rate
    * p_part    -- Bernoulli participation probability per cell
    * mu_shift  -- (2,) mean shift vector for joint events
    * Sigma_shift -- (2, 2) covariance of joint shift vectors

Marking probabilities (Bernoulli, independent across cells per event):

    p_{∅}   = (1 - p_part)^2
    p_{1}   = p_{2} = p_part * (1 - p_part)
    p_{1,2} = p_part^2

Marginal external rate per cell: ``lambda_X * p_part`` (each
external is marginally Poisson at this rate).

Cumulant structure
------------------
First cumulant:
    kappa^{(1)}_i = lambda_X * p_part = b_X        (constant per cell)

Cross-correlation cumulant density (the only nontrivial higher-order
cumulant for N=2):
    kappa^{(2)}_{12}(tau) = lambda_X * p_part^2 * Gauss(tau; mu_diff, sigma_diff^2)

with
    mu_diff       = mu_shift[1] - mu_shift[0]
    sigma_diff^2  = Sigma_shift[0,0] + Sigma_shift[1,1] - 2 * Sigma_shift[0,1]

Auto-cumulant (within-cell):
    kappa^{(2)}_{ii}(tau) = b_X * delta(tau)        (Poisson auto-corr)

Cumulants of order >= 3 vanish identically for N = 2 (no triplets
possible at this network size).

Status of the field-theory side
-------------------------------
**This model file is currently a SCAFFOLD.**  The action below is
identical to ``hawkes_quad_expg``'s action plus a constant
feedforward mean folded into ``E_i`` (so the existing pipeline runs
unchanged and treats the externals as if they were uncorrelated
mean drift).  The GTaS-specific cumulant structure has *not* yet
been wired into:

  * ``msrjd.core.field_theory.FieldTheory`` (no expansion of
    ``W_m[m̃]`` cumulant generating functional yet)
  * ``msrjd.integration.time_domain.propagator_td.build_G_t_matrix``
    (no ``δm̃-δm`` propagator block yet)
  * ``msrjd.diagrams.type_assignment`` (no NoiseVertexType yet)
  * ``msrjd.integration.time_domain.final_integral`` (no non-local
    kernel handler in Phase J yet)

Until those pieces land, the **theory side will under-predict the
sim cross-covariance** by exactly the GTaS contribution — that
mismatch is the validation target for the next commits.

The new model parameters are listed in ``parameters`` (so the
framework's symbol-discovery code sees them and the cache key
distinguishes this model from ``hawkes_quad_expg``), and a
documentation-only ``external_correlations`` block is included for
future field-theory code to consume.

Usage
-----
Drop-in alongside ``hawkes_quad_expg``:

    from models.hawkes_quad_expg_gtas import HAWKES_MODEL
    ft = FieldTheory(HAWKES_MODEL, taylor_order=4)

The notebook ``notebooks/hawkes_td_quad_gtas.ipynb`` is a fresh
clone configured for this model.
"""

from sage.all import SR, exp, function, I

# ---------------------------------------------------------------------------
# Population count (cortical only — externals are scalar-indexed below)
# ---------------------------------------------------------------------------
N_POP = 2
_pop  = list(range(N_POP))

# ---------------------------------------------------------------------------
# SR parameter symbols
# ---------------------------------------------------------------------------
_nstar = [SR.var(f'nstar{i+1}', domain='positive') for i in _pop]
_w     = [[SR.var(f'w{i+1}{j+1}') for j in _pop] for i in _pop]
_g     = SR.var('g')

# ---------------------------------------------------------------------------
# Model dict
# ---------------------------------------------------------------------------
HAWKES_MODEL: dict = {

    'name': ('Quadratic Hawkes 2-pop + GTaS external (phi = a v^2, '
             'exp filter tau_g, Bernoulli + Gaussian shifts)'),

    # -----------------------------------------------------------------------
    # Index sets
    # -----------------------------------------------------------------------
    'index_sets': {'pop': _pop},

    # -----------------------------------------------------------------------
    # Response fields  (full integration variables) — UNCHANGED from
    # hawkes_quad_expg.  The future ``mt`` (m-tilde) response field
    # will be added here when the field-theory side learns about it.
    # -----------------------------------------------------------------------
    'response_fields': [
        {'name': 'nt', 'indexed': True, 'latex': r'\tilde{n}',
         'description': 'response field conjugate to spike train'},
        {'name': 'vt', 'indexed': True, 'latex': r'\tilde{v}',
         'description': 'response field conjugate to voltage'},
    ],

    # -----------------------------------------------------------------------
    # Physical fluctuation fields  (expanded around MF background) —
    # UNCHANGED.  Future: ``dm`` (delta m) for the correlated external
    # spike fluctuation field will be added.
    # -----------------------------------------------------------------------
    'physical_fields': [
        {'name': 'dn', 'indexed': True, 'latex': r'\delta\dot{n}',
         'description': 'spike-train fluctuation around MF background'},
        {'name': 'dv', 'indexed': True, 'latex': r'\delta v',
         'description': 'voltage fluctuation around MF background'},
    ],

    # -----------------------------------------------------------------------
    # Scalar parameters
    #
    # Cortical (unchanged from hawkes_quad_expg):
    #   a, tau_g, tau, E, w, nstar, vstar
    #
    # NEW for GTaS (currently appear only as numerical inputs to the
    # MF voltage shift; future field-theory work will route these
    # through W_m[m̃] cumulants):
    #   W_X        -- one-to-one feedforward weight (external -> cortical)
    #   lambda_X   -- mother Poisson rate of the GTaS process
    #   p_part     -- Bernoulli participation probability per cell
    #   mu_shift_diff   -- mu_shift[1] - mu_shift[0]   (scalar)
    #   sigma_shift_diff_sq -- Sigma[0,0] + Sigma[1,1] - 2 Sigma[0,1]
    #
    # The two ``_diff`` parameters are the canonical GTaS reductions
    # (only mu_diff and sigma_diff matter for the kappa^(2)_{12}
    # kernel; absolute mu and full Sigma do not).
    # -----------------------------------------------------------------------
    'parameters': [
        {'name': 'nstar', 'indexed': True,  'domain': 'positive',
         'description': 'background firing rate  n*_i = a (v*_i)^2'},
        {'name': 'vstar', 'indexed': True,
         'description': 'background voltage'},
        {'name': 'E',     'indexed': True,
         'description': 'external constant drive (cortical)'},
        {'name': 'tau',   'indexed': False, 'domain': 'positive',
         'description': 'membrane time constant'},
        {'name': 'a',     'indexed': False,
         'description': 'quadratic transfer-function gain: phi(v) = a v^2'},
        {'name': 'tau_g', 'indexed': False, 'domain': 'positive',
         'description': 'synaptic exponential filter timescale'},
        {'name': 'w',     'indexed': True,
         'description': 'recurrent synaptic weight matrix w_{ij}'},
        # ---- GTaS external-layer parameters (new) ----
        {'name': 'W_X',   'indexed': False,
         'description': 'feedforward synaptic weight (external -> cortical, '
                        'one-to-one)'},
        {'name': 'lambda_X', 'indexed': False, 'domain': 'positive',
         'description': 'mother Poisson rate of GTaS external process'},
        {'name': 'p_part',   'indexed': False, 'domain': 'positive',
         'description': 'Bernoulli participation probability per external cell'},
        {'name': 'mu_shift_diff',     'indexed': False,
         'description': 'mean shift difference between externals: '
                        'mu_shift[1] - mu_shift[0]'},
        {'name': 'sigma_shift_diff_sq', 'indexed': False, 'domain': 'positive',
         'description': 'variance of shift difference: Sigma[0,0] + '
                        'Sigma[1,1] - 2 Sigma[0,1]'},
    ],

    # -----------------------------------------------------------------------
    # Kernels
    # -----------------------------------------------------------------------
    'kernels': [
        {'name': 'g', 'sage_name': 'z_g', 'latex_name': 'g',
         'description': 'exponential synaptic filter, unit integral'},
    ],

    # -----------------------------------------------------------------------
    # Operators
    # -----------------------------------------------------------------------
    'operators': [
        {'name': 'Dt', 'sage_name': 'Dt', 'latex_name': r'\partial_t',
         'description': r'd/dt  (time derivative)'},
    ],

    # -----------------------------------------------------------------------
    # Nonlinear functions  (unchanged)
    # -----------------------------------------------------------------------
    'functions': [
        {
            'name':         'phi',
            'indexed':      True,
            'deriv_prefix': 'phi',
            'latex':        r'\varphi',
            'description':  'quadratic gain function phi_i(v) = a v^2',
            'expression':   lambda i, v: function(f'phi_{i+1}')(v),
        },
    ],

    # -----------------------------------------------------------------------
    # Namespace-level substitutions
    # -----------------------------------------------------------------------
    'mf_substitutions': [
        {
            'name':  'w',
            'value': lambda ns: [[SR.var(f'w{i+1}{j+1}') for j in ns.pop]
                                 for i in ns.pop],
        },
        {
            'name':  'ndot_bg',
            'value': lambda ns: [+ns.nstar[i] for i in ns.pop],
        },
    ],

    # -----------------------------------------------------------------------
    # MF background conditions
    #
    # Cortical voltage now includes the GTaS feedforward mean:
    #   v*_i = E_i + sum_j w_{ij} g n*_j   +   W_X * (lambda_X * p_part)
    #                                       \____________________/
    #                                       feedforward mean (constant)
    #
    # The feedforward mean is the constant marginal external rate
    # b_X = lambda_X * p_part, fed through the unit-integral filter g
    # (so the time-integrated contribution is just W_X * b_X).
    # -----------------------------------------------------------------------
    'mf_bg_conditions': lambda ns: {
        **{SR.var(f'phi0_{i+1}'): ns.nstar[i] for i in ns.pop},
        **{ns.vstar[i]: (ns.E[i]
                         + sum(ns.w[i][j] * ns.g * ns.nstar[j]
                               for j in ns.pop)
                         + SR.var('W_X') * SR.var('lambda_X') * SR.var('p_part'))
           for i in ns.pop},
    },

    # -----------------------------------------------------------------------
    # Specializations  (unchanged from quad_expg)
    # -----------------------------------------------------------------------
    'specializations': lambda ns: {
        **{SR.var(f'phi1_{i+1}'): 2 * SR.var('a') * ns.vstar[i]
           for i in ns.pop},
        **{SR.var(f'phi2_{i+1}'): 2 * SR.var('a') for i in ns.pop},
        **{SR.var(f'phi{k}_{i+1}'): SR(0)
           for k in range(3, ns._taylor_order + 1)
           for i in ns.pop},
    },

    # -----------------------------------------------------------------------
    # Kernel frequency-space image  (unchanged)
    # -----------------------------------------------------------------------
    'kernel_ft_image': lambda ns, omega: {
        ns.g: SR(1) / (SR(1) + I * omega * ns.tau_g),
    },

    # -----------------------------------------------------------------------
    # Concrete transfer function  (unchanged)
    # -----------------------------------------------------------------------
    'phi_concrete': lambda ns, i, v: SR.var('a') * v**2,

    # -----------------------------------------------------------------------
    # Mean-field self-consistency equations
    # n*_i = a * (E_i + sum_j w_{ij} * n*_j + W_X * lambda_X * p_part)^2
    # -----------------------------------------------------------------------
    'mf_equations': lambda ns: [
        ns.nstar[i] == SR.var('a') * (
            ns.E[i]
            + sum(ns.w[i][j] * ns.nstar[j] for j in ns.pop)
            + SR.var('W_X') * SR.var('lambda_X') * SR.var('p_part')
        )**2
        for i in ns.pop
    ],

    # -----------------------------------------------------------------------
    # Background rate convention
    # -----------------------------------------------------------------------
    'background_rate_convention': (
        'n_dot_i* = +phi_i(v_i*) = a * (v_i*)^2     '
        '[Hawkes saddle, with feedforward mean shift '
        ' v*_i += W_X * lambda_X * p_part]'
    ),

    # -----------------------------------------------------------------------
    # Action
    #
    # Identical to hawkes_quad_expg's action.  The GTaS feedforward
    # appears only via the constant ``vstar`` shift in
    # ``mf_bg_conditions`` for now.  When the field-theory side gains
    # support for non-local interaction vertices, this will gain:
    #
    #   + ns.mt[i]^T * ns.dm[i]                              (free term)
    #   - ns.vt[i] * (ns.W_X * ns.g * ns.dm[sigma(i)])       (coupling)
    #   + cumulant W_m[m̃] series                             (vertices)
    # -----------------------------------------------------------------------
    'action': lambda ns: sum(
        ns.nt[i] * (ns.ndot_bg[i] + ns.dn[i])
        - (exp(ns.nt[i]) - 1) * ns.phi(i, ns.dv[i])
        + ns.vt[i] * (
            (ns.tau * ns.Dt + 1) * ns.dv[i]
            + ns.vstar[i] - ns.E[i]
            - sum(ns.w[i][j] * ns.g * (ns.nstar[j] + ns.dn[j])
                  for j in ns.pop)
            - SR.var('W_X') * ns.g * SR.var('lambda_X') * SR.var('p_part')
        )
        for i in ns.pop
    ),

    # -----------------------------------------------------------------------
    # External correlations spec  (DOCUMENTATION ONLY, not yet consumed
    # by the field-theory pipeline).  Future field-theory code can
    # iterate over ``cumulants`` to generate noise-vertex types.
    #
    # Each entry describes one nontrivial cumulant kernel of the GTaS
    # process.  ``order`` = chi (the cumulant order); ``indices`` lists
    # which external cells the cumulant connects; ``kernel`` is a
    # symbolic expression in time-lag variables tau_2, ..., tau_chi.
    # -----------------------------------------------------------------------
    'external_correlations': {
        'one_to_one_map': lambda ns: {i: i for i in ns.pop},
        'feedforward_weight_symbol': 'W_X',
        'mean_rate_per_cell': lambda ns: SR.var('lambda_X') * SR.var('p_part'),
        'cumulants': [
            {
                'order': 2,
                'indices': (0, 1),
                # kappa^(2)_{12}(tau) = lambda_X * p_part^2 *
                #   N(tau; mu_shift_diff, sigma_shift_diff_sq)
                'kernel_type': 'gaussian',
                'amplitude': lambda ns: (SR.var('lambda_X')
                                         * SR.var('p_part')**2),
                'mean_symbol':     'mu_shift_diff',
                'variance_symbol': 'sigma_shift_diff_sq',
            },
        ],
    },
}
