"""
models/hawkes_quad_expg_gtas.py
===============================
**Quadratic** Hawkes 2-population network *with two correlated
external neurons* generated by a GTaS (Generalized Thinning and
Shift) process — Bernoulli participation + Gaussian shifts.  Each
external neuron projects feedforward (one-to-one) to a single
cortical neuron with weight ``w_X`` through the same exponential
synaptic filter ``g(t) = (1/tau_g) exp(-t/tau_g) Theta(t)`` used
recurrently.

Network topology
----------------
    external[1] ──J──▶ cortical[1]
    external[2] ──J──▶ cortical[2]            (one-to-one feedforward)
    cortical[1] ⇄ cortical[2]                 (recurrent quadratic Hawkes)

Cortical layer (unchanged from ``hawkes_quad_expg``)
----------------------------------------------------
    phi_i(v) = a v^2     (quadratic gain)
    n*_i = phi_i(v*_i) = a (v*_i)^2
    v*_i = E_i + sum_j w_{ij} n*_j  +  w_X * (lambda_X * p_part)
                                    \____________________/
                                    constant feedforward mean

External GTaS process (Trousdale et al. 2013)
---------------------------------------------
A 2-cell GTaS process is fully characterised here by:

    * lambda_X  -- mother Poisson rate
    * p_part    -- Bernoulli participation probability per cell
    * mu_shift  -- (2,) mean shift vector for joint events
    * Sigma_shift -- (2, 2) covariance of joint shift vectors

Marking probabilities (Bernoulli, independent across cells per event):

    p_{∅}   = (1 - p_part)^2
    p_{1}   = p_{2} = p_part * (1 - p_part)
    p_{1,2} = p_part^2

Marginal external rate per cell: ``lambda_X * p_part`` (each
external is marginally Poisson at this rate).

Cumulant structure
------------------
First cumulant:
    kappa^{(1)}_i = lambda_X * p_part = b_X        (constant per cell)

Cross-correlation cumulant density (the only nontrivial higher-order
cumulant for N=2):
    kappa^{(2)}_{12}(tau) = lambda_X * p_part^2 * Gauss(tau; mu_diff, sigma_diff^2)

with
    mu_diff       = mu_shift[1] - mu_shift[0]
    sigma_diff^2  = Sigma_shift[0,0] + Sigma_shift[1,1] - 2 * Sigma_shift[0,1]

Auto-cumulant (within-cell):
    kappa^{(2)}_{ii}(tau) = b_X * delta(tau)        (Poisson auto-corr)

Cumulants of order >= 3 vanish identically for N = 2 (no triplets
possible at this network size).

Status of the field-theory side
-------------------------------
**Spike v0 (Option A — write the action, pull out vertices
automatically).**  This model file declares the GTaS coupling
**inside the action lambda** — the user writes ``ns.dm[i]`` and
``ns.mt[i]`` directly, just like ordinary physical / response
fields.  The non-local cumulant statistics live in a separate
``correlated_noises`` block (declarative, one place per noise
process).  The constant feedforward mean is absorbed into
``vstar`` via ``mf_bg_conditions`` so ``dm[i]`` is the
*fluctuation* (zero-mean by construction).

What's wired up at v0:

  * Field symbols ``ns.dm[i]`` (physical) and ``ns.mt[i]``
    (response) — recognised by ``FieldTheory._build_namespace`` as
    ordinary indexed fields, so the cortical/local part of the
    action expands and bigrades correctly.
  * ``correlated_noises`` block — declarative spec the expander
    will read to inject the cumulant series ``-W_m[mt]`` in the
    next commit.
  * Saddle shift ``v* += w_X * b_X`` retained in
    ``mf_bg_conditions``.

What's still missing (next commits):

  * ``FieldTheory.expand`` does not yet read ``correlated_noises``
    and append ``-W_m[mt]`` to the action — until then, the
    (n_tilde >= 2, 0) sectors will *not* contain GTaS noise
    vertices, so the theory still under-predicts the sim cross-
    covariance.
  * ``NoiseVertexType`` / leg-indexed time map / Phase J Gaussian
    integration — pipeline plumbing for non-local kernels.

Until the cumulant-injection commit lands, FieldTheory.expand()
runs to completion on this model but the noise side is still
trivial — useful for sanity-checking the (1,1) free action (the
new ``mt-dm`` block + ``vt-dm`` coupling).

Usage
-----
Drop-in alongside ``hawkes_quad_expg``:

    from models.hawkes_quad_expg_gtas import HAWKES_MODEL
    ft = FieldTheory(HAWKES_MODEL, taylor_order=4)

The notebook ``notebooks/hawkes_td_quad_gtas.ipynb`` is a fresh
clone configured for this model.
"""

from sage.all import SR, exp, function, I, sqrt, pi, dirac_delta


# ---------------------------------------------------------------------------
# Local helper: Gaussian kernel  N(tau; mu, sigma^2)
# ---------------------------------------------------------------------------
def _gauss(tau, mu, sigma_sq):
    """Unit-area Gaussian density used by the GTaS cross-cumulant kernel."""
    return exp(-(tau - mu)**2 / (2 * sigma_sq)) / sqrt(2 * pi * sigma_sq)

# ---------------------------------------------------------------------------
# Population count (cortical only — externals are scalar-indexed below)
# ---------------------------------------------------------------------------
N_POP = 2
_pop  = list(range(N_POP))

# ---------------------------------------------------------------------------
# SR parameter symbols
# ---------------------------------------------------------------------------
_nstar = [SR.var(f'nstar{i+1}', domain='positive') for i in _pop]
_w     = [[SR.var(f'w{i+1}{j+1}') for j in _pop] for i in _pop]
_g     = SR.var('g')

# ---------------------------------------------------------------------------
# Model dict
# ---------------------------------------------------------------------------
HAWKES_MODEL: dict = {

    'name': ('Quadratic Hawkes 2-pop + GTaS external (phi = a v^2, '
             'exp filter tau_g, Bernoulli + Gaussian shifts)'),

    # -----------------------------------------------------------------------
    # Index sets
    # -----------------------------------------------------------------------
    'index_sets': {'pop': _pop},

    # -----------------------------------------------------------------------
    # Response fields  (full integration variables)
    #
    # ``nt``, ``vt`` — cortical conjugates (unchanged from hawkes_quad_expg).
    # ``mt``        — conjugate of the GTaS external fluctuation field
    #                  ``dm``.  Declared here so the user can write
    #                  ``ns.mt[i]`` directly in the action lambda;
    #                  the cumulant series ``-W_m[mt]`` is auto-injected
    #                  by the FieldTheory expander using the
    #                  ``correlated_noises`` block below (Option A: one
    #                  place to write the physics).
    # -----------------------------------------------------------------------
    'response_fields': [
        {'name': 'nt', 'indexed': True, 'latex': r'\tilde{n}',
         'description': 'response field conjugate to spike train'},
        {'name': 'vt', 'indexed': True, 'latex': r'\tilde{v}',
         'description': 'response field conjugate to voltage'},
        {'name': 'mt', 'indexed': True, 'latex': r'\tilde{m}',
         'description': 'response field conjugate to GTaS external '
                        'fluctuation dm (one per cortical leg)'},
    ],

    # -----------------------------------------------------------------------
    # Physical fluctuation fields  (expanded around MF background)
    #
    # ``dn``, ``dv`` — cortical fluctuations (unchanged).
    # ``dm``        — GTaS external fluctuation, *zero-mean by
    #                  construction*.  The constant mean ``b_X = lambda_X *
    #                  p_part`` is folded into ``vstar`` via
    #                  ``mf_bg_conditions``; ``dm[i]`` represents the
    #                  fluctuation around that mean.  Treated like any
    #                  other physical field at the namespace level: gets
    #                  Taylor-expanded around 0 and contributes to the
    #                  bigrade analysis.  Its (non-Gaussian) statistics
    #                  enter via the ``correlated_noises`` block below.
    # -----------------------------------------------------------------------
    'physical_fields': [
        {'name': 'dn', 'indexed': True, 'latex': r'\delta\dot{n}',
         'description': 'spike-train fluctuation around MF background'},
        {'name': 'dv', 'indexed': True, 'latex': r'\delta v',
         'description': 'voltage fluctuation around MF background'},
        {'name': 'dm', 'indexed': True, 'latex': r'\delta m',
         'description': 'GTaS external fluctuation around mean b_X = '
                        'lambda_X * p_part (one per cortical leg, '
                        'zero-mean by construction)'},
    ],

    # -----------------------------------------------------------------------
    # Scalar parameters
    #
    # Cortical (unchanged from hawkes_quad_expg):
    #   a, tau_g, tau, E, w, nstar, vstar
    #
    # NEW for GTaS (currently appear only as numerical inputs to the
    # MF voltage shift; future field-theory work will route these
    # through W_m[m̃] cumulants):
    #   w_X        -- one-to-one feedforward weight (external -> cortical)
    #   lambda_X   -- mother Poisson rate of the GTaS process
    #   p_part     -- Bernoulli participation probability per cell
    #   mu_shift_diff   -- mu_shift[1] - mu_shift[0]   (scalar)
    #   sigma_shift_diff_sq -- Sigma[0,0] + Sigma[1,1] - 2 Sigma[0,1]
    #
    # The two ``_diff`` parameters are the canonical GTaS reductions
    # (only mu_diff and sigma_diff matter for the kappa^(2)_{12}
    # kernel; absolute mu and full Sigma do not).
    # -----------------------------------------------------------------------
    'parameters': [
        {'name': 'nstar', 'indexed': True,  'domain': 'positive',
         'description': 'background firing rate  n*_i = a (v*_i)^2'},
        {'name': 'vstar', 'indexed': True,
         'description': 'background voltage'},
        {'name': 'mstar', 'indexed': True, 'domain': 'positive',
         'description': 'background external rate  m*_i = b_X = '
                        'lambda_X * p_part (marginal Poisson rate per '
                        'external cell)'},
        {'name': 'E',     'indexed': True,
         'description': 'external constant drive (cortical)'},
        {'name': 'tau',   'indexed': False, 'domain': 'positive',
         'description': 'membrane time constant'},
        {'name': 'a',     'indexed': False,
         'description': 'quadratic transfer-function gain: phi(v) = a v^2'},
        {'name': 'tau_g', 'indexed': False, 'domain': 'positive',
         'description': 'synaptic exponential filter timescale'},
        {'name': 'w',     'indexed': True,
         'description': 'recurrent synaptic weight matrix w_{ij}'},
        # ---- GTaS external-layer parameters (new) ----
        {'name': 'w_X',   'indexed': False,
         'description': 'feedforward synaptic weight (external -> cortical, '
                        'one-to-one)'},
        {'name': 'lambda_X', 'indexed': False, 'domain': 'positive',
         'description': 'mother Poisson rate of GTaS external process'},
        {'name': 'p_part',   'indexed': False, 'domain': 'positive',
         'description': 'Bernoulli participation probability per external cell'},
        {'name': 'mu_shift_diff',     'indexed': False,
         'description': 'mean shift difference between externals: '
                        'mu_shift[1] - mu_shift[0]'},
        {'name': 'sigma_shift_diff_sq', 'indexed': False, 'domain': 'positive',
         'description': 'variance of shift difference: Sigma[0,0] + '
                        'Sigma[1,1] - 2 Sigma[0,1]'},
    ],

    # -----------------------------------------------------------------------
    # Kernels
    # -----------------------------------------------------------------------
    'kernels': [
        {'name': 'g', 'sage_name': 'z_g', 'latex_name': 'g',
         'description': 'exponential synaptic filter, unit integral'},
    ],

    # -----------------------------------------------------------------------
    # Operators
    # -----------------------------------------------------------------------
    'operators': [
        {'name': 'Dt', 'sage_name': 'Dt', 'latex_name': r'\partial_t',
         'description': r'd/dt  (time derivative)'},
    ],

    # -----------------------------------------------------------------------
    # Nonlinear functions  (unchanged)
    # -----------------------------------------------------------------------
    'functions': [
        {
            'name':         'phi',
            'indexed':      True,
            'deriv_prefix': 'phi',
            'latex':        r'\varphi',
            'description':  'quadratic gain function phi_i(v) = a v^2',
            'expression':   lambda i, v: function(f'phi_{i+1}')(v),
        },
    ],

    # -----------------------------------------------------------------------
    # Namespace-level substitutions
    # -----------------------------------------------------------------------
    'mf_substitutions': [
        {
            'name':  'w',
            'value': lambda ns: [[SR.var(f'w{i+1}{j+1}') for j in ns.pop]
                                 for i in ns.pop],
        },
        {
            'name':  'ndot_bg',
            'value': lambda ns: [+ns.nstar[i] for i in ns.pop],
        },
    ],

    # -----------------------------------------------------------------------
    # MF background conditions
    #
    # Cortical voltage now includes the GTaS feedforward mean:
    #   v*_i = E_i + sum_j w_{ij} g n*_j   +   w_X * g * (lambda_X * p_part)
    #                                       \________________________/
    #                                       feedforward mean (constant
    #                                       through the unit-integral filter g)
    #
    # The ``g`` kernel symbol is kept on both terms so the saddle
    # cancels the action's feedforward block exactly at the symbolic
    # level (the constant-input limit ``g * const = const`` is applied
    # downstream, not here).  Tadpole sanity check passes only with
    # this exact symbolic match.
    # -----------------------------------------------------------------------
    'mf_bg_conditions': lambda ns: {
        **{SR.var(f'phi0_{i+1}'): ns.nstar[i] for i in ns.pop},
        **{ns.vstar[i]: (ns.E[i]
                         + sum(ns.w[i][j] * ns.g * ns.nstar[j]
                               for j in ns.pop)
                         + ns.w_X * ns.g * ns.lambda_X * ns.p_part)
           for i in ns.pop},
    },

    # -----------------------------------------------------------------------
    # Specializations  (unchanged from quad_expg)
    # -----------------------------------------------------------------------
    'specializations': lambda ns: {
        **{SR.var(f'phi1_{i+1}'): 2 * SR.var('a') * ns.vstar[i]
           for i in ns.pop},
        **{SR.var(f'phi2_{i+1}'): 2 * SR.var('a') for i in ns.pop},
        **{SR.var(f'phi{k}_{i+1}'): SR(0)
           for k in range(3, ns._taylor_order + 1)
           for i in ns.pop},
    },

    # -----------------------------------------------------------------------
    # Kernel frequency-space image  (unchanged)
    # -----------------------------------------------------------------------
    'kernel_ft_image': lambda ns, omega: {
        ns.g: SR(1) / (SR(1) + I * omega * ns.tau_g),
    },

    # -----------------------------------------------------------------------
    # Concrete transfer function  (unchanged)
    # -----------------------------------------------------------------------
    'phi_concrete': lambda ns, i, v: SR.var('a') * v**2,

    # -----------------------------------------------------------------------
    # Mean-field self-consistency equations
    #
    #   n*_i = a · (E_i + Σ_j w_{ij} · n*_j + w_X · lambda_X · p_part)^2
    #                                                              (cortical)
    #   m*_i = b_X = lambda_X · p_part                         (external)
    #
    # The cortical equation keeps ``lambda_X · p_part`` inline (the
    # value the action's mf_bg_conditions absorbs into vstar) so the
    # solve is identical to the historical one.  The external
    # equation ``m*_i = b_X`` is reported alongside, so the MF table
    # explicitly shows the GTaS mean rate per cell.
    # -----------------------------------------------------------------------
    'mf_equations': lambda ns: [
        ns.nstar[i] == SR.var('a') * (
            ns.E[i]
            + sum(ns.w[i][j] * ns.nstar[j] for j in ns.pop)
            + SR.var('w_X') * SR.var('lambda_X') * SR.var('p_part')
        )**2
        for i in ns.pop
    ] + [
        ns.mstar[i] == SR.var('lambda_X') * SR.var('p_part')
        for i in ns.pop
    ],

    # -----------------------------------------------------------------------
    # Background rate convention
    # -----------------------------------------------------------------------
    'background_rate_convention': (
        'n_dot_i* = +phi_i(v_i*) = a * (v_i*)^2,     '
        'm_dot_i* = b_X = lambda_X * p_part     '
        '[Hawkes cortical saddle + GTaS external mean]'
    ),

    # -----------------------------------------------------------------------
    # Action
    #
    # Same cortical structure as hawkes_quad_expg, plus the GTaS
    # external coupling.  Following Option A of the design:
    #
    #   * The user writes ``ns.dm[i]`` and ``ns.mt[i]`` directly in the
    #     action lambda — they look like ordinary physical / response
    #     fields.
    #   * The constant feedforward mean ``w_X * g * b_X`` is absorbed
    #     into ``vstar`` via ``mf_bg_conditions``; ``dm[i]`` here is the
    #     *fluctuation* around that mean (zero-mean by construction).
    #   * The MSR pairing ``+ mt[i] * dm[i]`` makes ``mt`` the conjugate
    #     of ``dm`` (delta-correlated propagator G_R(dm,mt) = δ(τ)).
    #   * The non-local cumulant series ``-W_m[mt]`` is **not** written
    #     here — it is auto-injected by the FieldTheory expander based
    #     on the ``correlated_noises`` block below.  That keeps "write
    #     the physics, pull out vertices automatically" as the user
    #     contract.
    # -----------------------------------------------------------------------
    'action': lambda ns: sum(
        # Cortical Poisson term  (unchanged)
        ns.nt[i] * (ns.ndot_bg[i] + ns.dn[i])
        - (exp(ns.nt[i]) - 1) * ns.phi(i, ns.dv[i])
        # Cortical voltage equation  (now driven by w_X * g * dm[i])
        + ns.vt[i] * (
            (ns.tau * ns.Dt + 1) * ns.dv[i]
            + ns.vstar[i] - ns.E[i]
            - sum(ns.w[i][j] * ns.g * (ns.nstar[j] + ns.dn[j])
                  for j in ns.pop)
            - ns.w_X * ns.g * (ns.lambda_X * ns.p_part + ns.dm[i])
        )
        # MSR source-pairing for the external fluctuation field
        + ns.mt[i] * ns.dm[i]
        for i in ns.pop
    ),

    # -----------------------------------------------------------------------
    # Correlated-noise declarations
    #
    # One entry per stochastic external process whose statistics are
    # specified by cumulants rather than by a kinetic equation.  The
    # FieldTheory expander reads this block and:
    #
    #   1. confirms the named ``physical_field`` and ``response_field``
    #      exist;
    #   2. registers cumulant kernels on the namespace
    #      (``ns._correlated_noises``);
    #   3. auto-appends ``-W_m[mt]`` (the cumulant generating
    #      functional) to the action so noise vertices appear in the
    #      (n_tilde >= 2, 0) bigrade sectors with the correct non-local
    #      kernels.  *Spike v0: the namespace and saddle wiring is
    #      live; the ``-W_m[mt]`` injection lands in the next commit.*
    #
    # ``cumulants[n]`` signature:  ``(ns, *indices, *taus) -> SR scalar``
    # where ``indices`` is an ``n``-tuple of leg indices (0-based,
    # matching the indexed physical-field's primary index set) and
    # ``taus`` is a length-``(n-1)`` tuple of relative time lags
    # ``tau_k = t_k - t_1`` (so the first time argument is implicit
    # via translation invariance).  The kernel can use ``dirac_delta``
    # for local pieces (e.g. Poisson auto-correlation).
    # -----------------------------------------------------------------------
    'correlated_noises': {
        'X': {
            'physical_field':  'dm',
            'response_field':  'mt',
            # First cumulant (mean rate per cell); informational here —
            # already absorbed into vstar via mf_bg_conditions.
            'mean': lambda ns: ns.lambda_X * ns.p_part,
            # Central cumulants (orders >= 2).  For a 2-cell GTaS with
            # Bernoulli participation + Gaussian shifts:
            #   * κ^{(2)} has nontrivial cross (Gaussian smear) and a
            #     local auto piece (Poisson b_X · δ).
            #   * κ^{(n>=3)} cross-cumulants VANISH (binary marking
            #     means a single mother event can produce at most one
            #     spike per cell, so ≥3 indices with at least two
            #     distinct cells require ≥2 mother events whose
            #     contributions are independent → connected = 0).
            #   * κ^{(n>=3)} AUTO-cumulants are b_X · δ(τ_1)…δ(τ_{n-1})
            #     — just the Poisson statistics of the marginal.
            'cumulants': {
                # κ^{(2)}_{ij}(τ) =
                #   {  b_X · δ(τ),                            i == j  (Poisson auto)
                #   {  λ_X · p_part^2 · N(τ; μ_diff, σ_diff²), i != j (GTaS cross)
                2: lambda ns, i, j, tau: (
                    ns.lambda_X * ns.p_part * dirac_delta(tau)
                    if i == j else
                    ns.lambda_X * ns.p_part**2 * _gauss(
                        tau, ns.mu_shift_diff, ns.sigma_shift_diff_sq
                    )
                ),
                # κ^{(3)}_{ijk}(τ_1, τ_2): only AUTO is nonzero.
                3: lambda ns, i, j, k, t1, t2: (
                    ns.lambda_X * ns.p_part
                    * dirac_delta(t1) * dirac_delta(t2)
                    if (i == j == k) else SR(0)
                ),
                # κ^{(4)}_{ijkl}(τ_1, τ_2, τ_3): only AUTO is nonzero.
                4: lambda ns, i, j, k, l, t1, t2, t3: (
                    ns.lambda_X * ns.p_part
                    * dirac_delta(t1) * dirac_delta(t2) * dirac_delta(t3)
                    if (i == j == k == l) else SR(0)
                ),
            },
        },
    },

}
